// autogenerated by 020-eslint-lpt-soften.cjs
// Мягкая LPT-конфигурация ESLint (flat, v9)
// Цель: локальные проверки без «красных» остановок на неключевых местах
// В CI/PR можно использовать основной строгий конфиг.

import js from '@eslint/js';
import tseslint from 'typescript-eslint';
import globals from 'globals';

export default [
  {
    files: ['**/*.cjs'],
    languageOptions: {
      sourceType: 'script',
      globals: { ...globals.node },
    },
    rules: {
      'no-undef': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },
  {
    // Перенос игноров из .eslintignore + служебные/генерируемые файлы
    ignores: [
      "patch_cjs/**",
  "pnpm-lock.yaml",
  "package.json",
  "eslint.lpt.config.ts",
  "src/db/queries.ts",
  "src/geo/osrm.ts",
  "src/routes/tasks.ts",
  "src/services/optimizer.ts",
  "src/services/wgLogEngine.ts",
  "src/tasks/uploadFinalizer.ts",
      'apps/web/postcss.config.cjs'
    ]
  },

  // Базовые рекомендации JS
  js.configs.recommended,

  // Блок для TypeScript/TSX (без type-check в LPT)
  ...tseslint.configs.recommended,

  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      ecmaVersion: 2022,
      sourceType: 'module',
      globals: {
        ...globals.browser,
        ...globals.node,
        ...globals.es2021
      }
    },
    rules: {
      'prefer-const': 'off',
      'react-refresh/only-export-components': 'off',
      // Послабления под LPT (локальная проверка, не прод-качество)
      'no-undef': 'off',
      'no-redeclare': 'off',

      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    }
  },

  // Тесты: ещё мягче
  {
    files: ['**/*.spec.ts', '**/*.spec.tsx', '**/*.test.ts', '**/*.test.tsx'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      '@typescript-eslint/no-require-imports': 'off',
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-redeclare': 'off',
    }
  },

  // декларационные файлы
  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/no-unused-vars': 'off',
      'no-undef': 'off',
    }
  },

  // vite / config-файлы
  {
    files: ['**/vite.config.ts', '**/*.config.ts'],
    rules: {
      'no-undef': 'off',
    }
  },
];
