// auto-generated by 018-eslint-lpt-soft
// Наследуем базовый flat-конфиг и ослабляем часть правил ТОЛЬКО для локального LPT
import base from './eslint.config.ts';

const LPT_OVERRIDES = [
  {
    files: ['apps/api/**/*.{ts,tsx}'],
    rules: {
      '@typescript-eslint/no-unused-vars': ['warn', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      'no-redeclare': 'warn',
    },
  },
];

const cfg = Array.isArray(base) ? [...base, ...LPT_OVERRIDES] : [base, ...LPT_OVERRIDES];
export default cfg;
