/**
 * Назначение файла: конфигурация pm2 для запуска API и бота.
 * Основные модули: pm2.
 */
module.exports = {
  apps: [
    {
      name: 'api',
      script: 'dist/server.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      restart_delay: 5000,
      max_memory_restart: '512M',
      out_file: '/var/log/pm2/api.out.log',
      error_file: '/var/log/pm2/api.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env_production: {
        NODE_ENV: 'production',
        QUEUE_REDIS_URL: process.env.QUEUE_REDIS_URL,
        TELEGRAM_WEBHOOK_URL: process.env.TELEGRAM_WEBHOOK_URL,
        TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
        QUEUE_CONCURRENCY: process.env.QUEUE_CONCURRENCY,
      },
    },
    {
      name: 'bot',
      script: 'dist/bot/runtime.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      restart_delay: 5000,
      max_memory_restart: '512M',
      out_file: '/var/log/pm2/bot.out.log',
      error_file: '/var/log/pm2/bot.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env_production: {
        NODE_ENV: 'production',
        QUEUE_REDIS_URL: process.env.QUEUE_REDIS_URL,
        TELEGRAM_WEBHOOK_URL: process.env.TELEGRAM_WEBHOOK_URL,
        TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
        QUEUE_CONCURRENCY: process.env.QUEUE_CONCURRENCY,
      },
    },
    {
      name: 'worker',
      script: '../worker/dist/index.js',
      cwd: __dirname,
      instances: 1,
      exec_mode: 'fork',
      watch: false,
      autorestart: true,
      max_restarts: 10,
      min_uptime: 5000,
      restart_delay: 5000,
      max_memory_restart: '512M',
      out_file: '/var/log/pm2/worker.out.log',
      error_file: '/var/log/pm2/worker.err.log',
      merge_logs: true,
      log_date_format: 'YYYY-MM-DD HH:mm:ss.SSS Z',
      env_production: {
        NODE_ENV: 'production',
        QUEUE_REDIS_URL: process.env.QUEUE_REDIS_URL,
        TELEGRAM_WEBHOOK_URL: process.env.TELEGRAM_WEBHOOK_URL,
        TELEGRAM_WEBHOOK_SECRET: process.env.TELEGRAM_WEBHOOK_SECRET,
        QUEUE_CONCURRENCY: process.env.QUEUE_CONCURRENCY,
      },
    },
  ],
};
