# Назначение файла: автоматический релиз при публикации тега
name: Release

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Включение corepack
        run: corepack enable
      - name: Установка зависимостей
        run: pnpm install --frozen-lockfile
      - name: Сборка пакетов
        run: pnpm -r build
      - name: Линтер и тесты перед релизом
        run: pnpm lint && pnpm test:unit && pnpm test:api
      - uses: docker/setup-buildx-action@v3
      - name: Сборка Docker-образа
        run: docker build -t task-bot .
      - name: Деплой на Railway
        run: pnpm dlx @railway/cli@latest up --service bot --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
