# Назначение файла: автоматический релиз при публикации тега
name: Release
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: ./scripts/install_bot_deps.sh
      - name: Включение corepack
        run: corepack enable
      - name: Установка зависимостей
        run: pnpm install --frozen-lockfile
      - name: Линтеры
        run: pnpm lint
      - name: Юнит и API тесты
        run: pnpm test:unit && pnpm test:api
      - name: Сборка пакетов
        run: pnpm -r build
      - uses: docker/setup-buildx-action@v3
      - name: Сборка Docker-образа
        run: docker build -t task-bot .
      - name: Установка Railway CLI
        run: npm install -g @railway/cli
      - name: Деплой на Railway
        run: railway up --service bot --detach
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      - uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
